apiVersion: v1
kind: Service
metadata:
  labels:
    app: springboot-demo
  name: springboot-demo
spec:
  ports:
  - name: intermapper
    port: 8181
    protocol: TCP
    targetPort: 8181
  selector:
    app: springboot-demo
